### ISSUE TITLE
Deleting element with a view causes orphaned View, can't compile

### ISSUE THREAD

**Issue by mgmhunt** [uFrame/uFrame.MVVM#2]
Various errors...can't compile using Build button although no console errors.

uFrame issue list has
'This view must have an element'
click on issue get 
'Workspace not found for ____ SystemGraph' appearing in editor.
'Object reference not set to an instance of object' appearing in editor.

Switching databases back and forth seemed to clear the issue?

I think this came about due to deleting an element via the 'placed system'.  ie the 'Show System' menu, gives a greyed out version of the system and you can view/edit this system but it seems to be in a referenced way.  If you open the system directly in a new tab I think it's much more stable.  This 'referenced' view has always seemed dodgy and I'd recommend locking it off so the only way to edit a system is via opening a new tab. ie show the referenced system node but don't allow double clicking to enter and/or edit.

`ArgumentException: An element with the same key already exists in the dictionary.
System.Collections.Generic.Dictionary`2[uFrame.Editor.Graphs.Data.IGraphFilter,UnityEngine.Vector2].Add (IGraphFilter key, Vector2 value) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:404)
uFrame.Editor.GraphUI.Drawers.DiagramDrawer.Refresh (IPlatformDrawer platform, Vector2 position, Boolean hardRefresh) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/Drawers/impl/DiagramDrawer.cs:631)
uFrame.Editor.GraphUI.Drawers.Drawer.Refresh (IPlatformDrawer platform) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/Drawers/api/Drawer.cs:81)
uFrame.Editor.GraphUI.DesignerWindow.RefreshContent () (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/DesignerWindow.cs:341)
uFrame.Editor.GraphUI.DesignerWindow.CommandExecuted (ICommand command) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/DesignerWindow.cs:469)
uFrame.Editor.Core.InvertApplication+<Execute>c__AnonStorey117`1[uFrame.Editor.Core.LambdaCommand].<>m__FD (ICommandExecuted _) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/InvertApplication.cs:407)
uFrame.Editor.Core.EventManager`1[uFrame.Editor.Core.ICommandExecuted].Signal (System.Action`1 action) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/EventManager.cs:30)
uFrame.Editor.Core.InvertApplication.SignalEvent[ICommandExecuted] (System.Action`1 action) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/InvertApplication.cs:377)
uFrame.Editor.Core.InvertApplication.Execute[LambdaCommand](uFrame.Editor.Core.LambdaCommand command) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/InvertApplication.cs:407)
uFrame.Editor.GraphUI.ViewModels.GraphDesignerNavigationViewModel+<Refresh>c__AnonStorey166.<>m__1C9 (Vector2 x) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/ViewModels/GraphDesignerNavigationViewModel.cs:79)
uFrame.Editor.GraphUI.Drawers.DiagramDrawer+<DrawTabs>c__AnonStorey148.<>m__17B (Vector2 m) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/Drawers/impl/DiagramDrawer.cs:136)
uFrame.Editor.Unity.UnityDrawer.DoButton (Rect scale, System.String label, System.Object style, System.Action`1 action, System.Action`1 rightClick) (at Assets/uFrame/uFrameCore/Editor/Systems/Unity/UnityDrawer.cs:178)
uFrame.Editor.GraphUI.Drawers.DiagramDrawer.DrawTabs (IPlatformDrawer platform, Rect tabsRect) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/Drawers/impl/DiagramDrawer.cs:134)
uFrame.Editor.GraphUI.DesignerWindow.Draw (Single width, Single height, Vector2 scrollPosition, Single scale) (at Assets/uFrame/uFrameCore/Editor/Systems/GraphUI/DesignerWindow.cs:170)
uFrame.Editor.Unity.UnityDesignerWindow+<DrawDesigner>c__AnonStorey1B9.<>m__27F (IDrawUFrameWindow _) (at Assets/uFrame/uFrameCore/Editor/Systems/Unity/UnityDesignerWindow.cs:97)
uFrame.Editor.Core.EventManager`1[uFrame.Editor.GraphUI.Events.IDrawUFrameWindow].Signal (System.Action`1 action) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/EventManager.cs:30)
uFrame.Editor.Core.InvertApplication.SignalEvent[IDrawUFrameWindow](System.Action`1 action) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/InvertApplication.cs:377)
uFrame.Editor.Unity.UnityDesignerWindow.DrawDesigner (Single width, Single height) (at Assets/uFrame/uFrameCore/Editor/Systems/Unity/UnityDesignerWindow.cs:97)
uFrame.Editor.Unity.ElementsDesigner.<OnGUI>m__25C (IDrawDesignerWindow _) (at Assets/uFrame/uFrameCore/Editor/Systems/Unity/ElementsDesigner.cs:43)
uFrame.Editor.Core.EventManager`1[uFrame.Editor.Unity.IDrawDesignerWindow].Signal (System.Action`1 action) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/EventManager.cs:30)
uFrame.Editor.Core.InvertApplication.SignalEvent[IDrawDesignerWindow](System.Action`1 action) (at Assets/uFrame/uFrameCore/Editor/Systems/Core/InvertApplication.cs:377)
uFrame.Editor.Unity.ElementsDesigner.OnGUI () (at Assets/uFrame/uFrameCore/Editor/Systems/Unity/ElementsDesigner.cs:43)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)`

**Comment by sdotyxz** [comment]
@mgmhunt  Please check https://trello.com/c/6LmNKnz1 in trello, problem is fixed and will be update in next release

**Comment by mgmhunt** [comment]
sure thanks, can you add me to Trello board? my handle on Trello is mgmhunt. still think maybe a preference option (on by default) to lock off referenced elements so the only way to edit a system is via opening a new tab. ie show the referenced system node but don't allow double clicking to enter and/or edit.  Will add it to Trello board as request once a member.

Also just wary of splitting the bug reports between repository and Trello... seems more open/clear to use GitHub doesn't it??  Plus reporting Issues on Architect branch vs MVVM vs All-In-One... dunno see a problem splitting conversation between Gitter/GitHub/Trello/multiple branches. difficult to know where to find everybody/report and contribute.

**Comment by sdotyxz** [comment]
@mgmhunt actually you can raise issue in All In One, I have link that repo with the trello board

**Comment by mgmhunt** [comment]
oh ok, thanks will use that one from now on
